import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Subject, WhatIfResult, RecoveryInfo, calculateAttendancePercentage, calculateOverallAttendance } from '@/types/attendance';

interface AttendancePDFData {
  subjects: Subject[];
  whatIfResults?: WhatIfResult[];
  recoveryInfos?: RecoveryInfo[];
  scenarioDescription?: string;
}

export const exportAttendanceToPDF = (data: AttendancePDFData) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // Title
  doc.setFontSize(20);
  doc.setTextColor(99, 102, 241); // Primary color
  doc.text('Attendance Report', pageWidth / 2, 20, { align: 'center' });
  
  // Date
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(`Generated on: ${new Date().toLocaleDateString()}`, pageWidth / 2, 28, { align: 'center' });
  
  let yPosition = 40;
  
  // Subject-wise Attendance Table
  doc.setFontSize(14);
  doc.setTextColor(0, 0, 0);
  doc.text('Subject-wise Attendance', 14, yPosition);
  yPosition += 5;
  
  const subjectData = data.subjects.map(subject => {
    const percentage = calculateAttendancePercentage(subject.attendedClasses, subject.totalClasses);
    const status = percentage >= 75 ? 'Safe' : 'At Risk';
    return [
      subject.name || 'Unnamed',
      subject.totalClasses.toString(),
      subject.attendedClasses.toString(),
      `${percentage.toFixed(1)}%`,
      status,
    ];
  });
  
  autoTable(doc, {
    startY: yPosition,
    head: [['Subject', 'Total Classes', 'Attended', 'Percentage', 'Status']],
    body: subjectData,
    theme: 'striped',
    headStyles: { fillColor: [99, 102, 241] },
    columnStyles: {
      4: { 
        cellWidth: 25,
        fontStyle: 'bold',
      }
    },
    didParseCell: (data) => {
      if (data.section === 'body' && data.column.index === 4) {
        const cellValue = data.cell.raw as string;
        if (cellValue === 'At Risk') {
          data.cell.styles.textColor = [220, 38, 38];
        } else {
          data.cell.styles.textColor = [34, 197, 94];
        }
      }
    },
  });
  
  yPosition = (doc as any).lastAutoTable.finalY + 15;
  
  // Overall Attendance
  const overall = calculateOverallAttendance(data.subjects);
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  doc.text(`Overall Attendance: ${overall.percentage.toFixed(1)}%`, 14, yPosition);
  doc.text(`(${overall.attended} / ${overall.total} classes)`, 14, yPosition + 6);
  
  yPosition += 20;
  
  // What-If Results
  if (data.whatIfResults && data.whatIfResults.length > 0) {
    doc.setFontSize(14);
    doc.text('What-If Scenario Results', 14, yPosition);
    
    if (data.scenarioDescription) {
      doc.setFontSize(10);
      doc.setTextColor(100, 100, 100);
      yPosition += 6;
      doc.text(data.scenarioDescription, 14, yPosition);
      doc.setTextColor(0, 0, 0);
    }
    
    yPosition += 5;
    
    const whatIfData = data.whatIfResults.map(result => [
      result.subjectName,
      `${result.originalPercentage.toFixed(1)}%`,
      `${result.newPercentage.toFixed(1)}%`,
      `${result.change >= 0 ? '+' : ''}${result.change.toFixed(1)}%`,
    ]);
    
    autoTable(doc, {
      startY: yPosition,
      head: [['Subject', 'Before', 'After', 'Change']],
      body: whatIfData,
      theme: 'striped',
      headStyles: { fillColor: [234, 179, 8] },
      didParseCell: (data) => {
        if (data.section === 'body' && data.column.index === 3) {
          const cellValue = data.cell.raw as string;
          if (cellValue.startsWith('-')) {
            data.cell.styles.textColor = [220, 38, 38];
          } else {
            data.cell.styles.textColor = [34, 197, 94];
          }
        }
      },
    });
    
    yPosition = (doc as any).lastAutoTable.finalY + 15;
  }
  
  // Recovery Recommendations
  if (data.recoveryInfos && data.recoveryInfos.length > 0) {
    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.text('Recovery Recommendations', 14, yPosition);
    yPosition += 5;
    
    const recoveryData = data.recoveryInfos.map(info => [
      info.subjectName,
      `${info.currentPercentage.toFixed(1)}%`,
      `${info.classesNeeded} classes`,
    ]);
    
    autoTable(doc, {
      startY: yPosition,
      head: [['Subject', 'Current %', 'Classes Needed for 75%']],
      body: recoveryData,
      theme: 'striped',
      headStyles: { fillColor: [220, 38, 38] },
    });
  }
  
  // Footer
  const pageHeight = doc.internal.pageSize.getHeight();
  doc.setFontSize(9);
  doc.setTextColor(150, 150, 150);
  doc.text('Generated by Smart Attendance Calculator | TEAMDINO', pageWidth / 2, pageHeight - 10, { align: 'center' });
  
  doc.save('attendance-report.pdf');
};
